const REQUEST_FAILURE = 'REQUEST_FAILURE' //异步获取数据失败
const RECEIVE_STATUS = 'RECEIVE_STATUS' //获取异步返回的状态码

const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS' //异步获取购物车清单
const GET_PRODUCTS = 'GET_PRODUCTS' //触发获取购物车的action
const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS' //已获取购物车清单

const SELECT_BOOK = 'SELECT_BOOK' //选中书籍
const SELECT_BOOK_ALL = 'SELECT_BOOK_ALL' //全选
const EDIT_BOOK_COUNT = 'EDIT_BOOK_COUNT' //编辑购物车书籍数量
const DELETE_BOOK = 'DELETE_BOOK' //删除购物车中的书籍
const COMPUTED_COURT_COUNT = 'COMPUTED_COURT_COUNT' //计算购物车书籍数量
const COMPUTED_COURT_MONEY = 'COMPUTED_COURT_MONEY' //计算购物车选中的书的金额


export {
  RECEIVE_STATUS,
  REQUEST_FAILURE,
  RECEIVE_PRODUCTS,
  GET_PRODUCTS,
  REQUEST_PRODUCTS,
  EDIT_BOOK_COUNT,
  COMPUTED_COURT_COUNT,
  COMPUTED_COURT_MONEY,
  SELECT_BOOK,
  SELECT_BOOK_ALL,
  DELETE_BOOK
}