const REQUEST_FAILURE = 'REQUEST_FAILURE' //异步获取数据失败
const RECEIVE_STATUS = 'RECEIVE_STATUS' //获取异步返回的状态码

const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS' //异步获取购物车清单
const GET_PRODUCTS = 'GET_PRODUCTS' //触发获取购物车的action
const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS' //已获取购物车清单

const SELECT_BOOK = 'SELECT_BOOK' //选中书籍
const SELECT_BOOK_ALL = 'SELECT_BOOK_ALL' //全选
const EDIT_BOOK_COUNT = 'EDIT_BOOK_COUNT' //编辑购物车书籍数量
const DELETE_BOOK = 'DELETE_BOOK' //删除购物车中的书籍
const COMPUTED_COURT_COUNT = 'COMPUTED_COURT_COUNT' //计算购物车书籍数量
const COMPUTED_COURT_MONEY = 'COMPUTED_COURT_MONEY' //计算购物车选中的书的金额
const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS'

const GET_BOOK_MARKET = 'GET_BOOK_MARKET' //获取图书市场
const SEARCH_BOOK = 'SEARCH_BOOK' //搜索图书
const ADD_BOOK_TO_COURT = 'ADD_BOOK_TO_COURT' //添加图书到购物车
const GET_BOOK_SEARCH_RES = 'GET_BOOK_SEARCH_RES' //获取到匹配的书籍
const ADD_BOOK_TO_COURT_SUCCESS = 'ADD_BOOK_TO_COURT_SUCCESS' //成功加图书到购物车
const ADD_BOOK_TO_COURT_FAILURE = 'ADD_BOOK_TO_COURT_FAILURE' //加图书到购物车失败
const UPDATE_KEYWORD = 'UPDATE_KEYWORD' //更新搜索字段
const CLOSE_MESSAGE = 'CLOSE_MESSAGE' //关闭提示

const GET_BILL = 'GET_BILL' //获取账单
const GET_USER_INFO = 'GET_USER_INFO' //获取用户信息

const LOGIN_SUCCESS = 'LOGIN_SUCCESS' //登录成功
const LOGIN_FAILURE = 'LOGIN_FAILURE' //登录失败
const LOGIN_IN = 'LOGIN_IN' //登录
const LOGIN_OUT = 'LOGIN_OUT' //退出

const REGISTER_SUCCESS = 'REGISTER_SUCCESS' //注册成功
const REGISTER_FAILURE = 'REGISTER_FAILURE' //注册失败

const GET_BOOK_LIST_MANAGEMENT = 'GET_BOOK_LIST_MANAGEMENT' //获取书籍列表
const ADD_BOOK_MANAGEMENT = 'ADD_BOOK_MANAGEMENT' //添加书籍到书库
const EDIT_BOOK_MANAGEMENT = 'EDIT_BOOK_MANAGEMENT' //更新书籍信息
const DELETE_BOOK_MANAGEMENT = 'DELETE_BOOK_MANAGEMENT' //删除书籍
const FIND_BOOK_MANAGEMENT = 'FIND_BOOK_MANAGEMENT' //搜索书籍

const GET_USER_LIST_MANAGEMENT = 'GET_USER_LIST_MANAGEMENT' //获取会员列表

const GET_BILL_LIST_MANAGEMENT = 'GET_BILL_LIST_MANAGEMENT' //获取账单列表
const EDIT_BILL_MANAGEMENT = 'EDIT_BILL_MANAGEMENT' //处理账单



export {
  RECEIVE_STATUS,
  REQUEST_FAILURE,
  RECEIVE_PRODUCTS,
  GET_PRODUCTS,
  REQUEST_PRODUCTS,
  EDIT_BOOK_COUNT,
  COMPUTED_COURT_COUNT,
  COMPUTED_COURT_MONEY,
  SELECT_BOOK,
  SELECT_BOOK_ALL,
  DELETE_BOOK,
  ADD_BOOK_TO_COURT,
  GET_BOOK_MARKET,
  SEARCH_BOOK,
  GET_BOOK_SEARCH_RES,
  CLOSE_MESSAGE,
  ADD_BOOK_TO_COURT_FAILURE,
  ADD_BOOK_TO_COURT_SUCCESS,
  UPDATE_KEYWORD,
  GET_BILL,
  GET_USER_INFO,
  LOGIN_SUCCESS,
  LOGIN_OUT,
  LOGIN_IN,
  LOGIN_FAILURE,
  REGISTER_FAILURE,
  REGISTER_SUCCESS,
  GET_BILL_LIST_MANAGEMENT,
  GET_USER_LIST_MANAGEMENT,
  ADD_BOOK_MANAGEMENT,
  DELETE_BOOK_MANAGEMENT,
  EDIT_BILL_MANAGEMENT,
  EDIT_BOOK_MANAGEMENT,
  FIND_BOOK_MANAGEMENT,
  GET_BOOK_LIST_MANAGEMENT,
  PURCHASE_SUCCESS
}